const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const multer = require('multer');

module.exports = function registerControlCenter(ctx) {
  const { app, ROOT, PROJECT_ROOT, shops, orders, uploads, id, now, logActivity } = ctx;
  const DATA_DIR = path.join(ROOT, 'storage');
  const MEDIA_DIR = path.join(DATA_DIR, 'media');
  const DATA_FILE = path.join(DATA_DIR, 'control-center.json');
  fs.mkdirSync(MEDIA_DIR, { recursive: true });
  const defaultState = () => ({
    site: { platformName: 'Printer Auto', supportContact: '', logoMediaId: null, faviconMediaId: null, socialImageMediaId: null, announcement: '', privacyPolicy: '', terms: '', refundPolicy: '', helpContent: '' },
    banners: {}, media: {}, campaigns: {}, redemptions: {}, providerChanges: [], ai: { provider: 'openai-compatible', model: process.env.AI_MODEL || 'gpt-4o-mini', enabled: false, maxOutputTokens: 800, timeoutMs: 12000, dailyBudget: 0, allowedTools: ['platform_summary'], lastError: null, updatedAt: null },
    notifications: [], changes: []
  });
  const state = defaultState();
  try { Object.assign(state, JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'))); } catch {}
  state.site ||= defaultState().site; state.banners ||= {}; state.media ||= {}; state.campaigns ||= {}; state.redemptions ||= {}; state.notifications ||= []; state.changes ||= []; state.providerChanges ||= []; state.ai ||= defaultState().ai;
  const save = () => { fs.mkdirSync(DATA_DIR, { recursive: true }); fs.writeFileSync(DATA_FILE, JSON.stringify(state, null, 2)); };
  const audit = (req, action, metadata = {}) => { const safe = JSON.parse(JSON.stringify(metadata, (_, v) => typeof v === 'string' && v.length > 200 ? v.slice(0, 200) : v)); state.changes.unshift({ id: id('change'), action, actorId: req.superAdmin?.id || 'unknown', at: now(), metadata: safe }); state.changes = state.changes.slice(0, 5000); if (req.superAdmin) logActivity({ id: req.superAdmin.id, shopId: null }, `SUPER_ADMIN_${action}`, safe); save(); };
  const admin = app.locals.superAdminAuth;
  const adminOnly = (req, res, next) => admin(req, res, next);
  const str = (v, max = 240) => String(v ?? '').trim().slice(0, max);
  const status = v => ['DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'SCHEDULED', 'EXPIRED', 'ARCHIVED', 'ACTIVE', 'PAUSED', 'INACTIVE'].includes(String(v).toUpperCase()) ? String(v).toUpperCase() : null;
  const validUrl = value => { const u = str(value, 500); if (!u) return ''; if (u.startsWith('/') && !u.startsWith('//') && !u.includes('\\')) return u; try { const parsed = new URL(u); if (parsed.protocol !== 'https:') return null; const allowed = new Set(String(process.env.PUBLIC_URL_HOSTS || '').split(',').map(x => x.trim()).filter(Boolean)); return allowed.size && allowed.has(parsed.host) ? parsed.toString() : null; } catch { return null; } };
  const normalizeCode = value => str(value, 40).toUpperCase().replace(/\s+/g, '');
  const money = value => Math.round(Number(value) * 100) / 100;
  const dateValue = value => { const t = Date.parse(value); return Number.isFinite(t) ? new Date(t).toISOString() : null; };
  const asset = m => m ? { id: m.id, mimeType: m.mimeType, bytes: m.bytes, width: m.width, height: m.height, altText: m.altText, uploadedAt: m.uploadedAt, public: Boolean(m.public) } : null;
  const bannerRow = b => ({ ...b, desktop: asset(state.media[b.desktopMediaId]), mobile: asset(state.media[b.mobileMediaId]) });
  const campaignRow = c => ({ ...c, code: c.code, redemptions: Object.values(state.redemptions).filter(r => r.campaignId === c.id && r.status === 'REDEEMED').length });
  const safeCsv = value => { const s = String(value ?? ''); if (/^[=+\-@]/.test(s)) return `'${s}`; return /[",\n]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s; };
  const pngDimensions = b => b.length >= 24 && b.readUInt32BE(0) === 0x89504e47 ? { width: b.readUInt32BE(16), height: b.readUInt32BE(20) } : null;
  function jpegDimensions(b) { let i = 2; while (i + 9 < b.length) { if (b[i] !== 0xff) { i++; continue; } const marker = b[i + 1]; const len = b.readUInt16BE(i + 2); if ([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)) return { width: b.readUInt16BE(i + 7), height: b.readUInt16BE(i + 5) }; if (!len) break; i += 2 + len; } return null; }
  const mediaUpload = multer({ storage: multer.diskStorage({ destination: MEDIA_DIR, filename: (_, f, cb) => cb(null, `${crypto.randomBytes(18).toString('hex')}${path.extname(f.originalname).toLowerCase()}`) }), limits: { fileSize: 10 * 1024 * 1024, files: 1 }, fileFilter: (_, f, cb) => cb(null, ['image/png', 'image/jpeg', 'image/webp'].includes(f.mimetype)) });
  function mediaSignature(file) { const b = fs.readFileSync(file.path).subarray(0, 16); return (file.mimetype === 'image/png' && b.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) || (file.mimetype === 'image/jpeg' && b.subarray(0, 3).equals(Buffer.from([255,216,255]))) || (file.mimetype === 'image/webp' && b.subarray(0, 4).toString() === 'RIFF' && b.subarray(8, 12).toString() === 'WEBP'); }
  function usedMedia(idValue) { return Object.values(state.banners).some(b => b.desktopMediaId === idValue || b.mobileMediaId === idValue) || [state.site.logoMediaId, state.site.faviconMediaId, state.site.socialImageMediaId].includes(idValue); }

  app.get('/api/superadmin/control/site', adminOnly, (req, res) => res.json({ site: state.site }));
  app.put('/api/superadmin/control/site', adminOnly, (req, res) => { const input = req.body || {}; for (const k of ['platformName','supportContact','announcement','privacyPolicy','terms','refundPolicy','helpContent']) if (input[k] !== undefined) state.site[k] = str(input[k], k === 'platformName' ? 100 : 12000); for (const k of ['logoMediaId','faviconMediaId','socialImageMediaId']) if (input[k] !== undefined) { if (input[k] && !state.media[input[k]]) return res.status(400).json({ error: 'MEDIA_NOT_FOUND' }); state.site[k] = input[k] || null; } audit(req, 'SITE_SETTINGS_CHANGED', { fields: Object.keys(input) }); res.json({ site: state.site }); });

  app.get('/api/superadmin/media', adminOnly, (req, res) => res.json({ media: Object.values(state.media).map(m => ({ ...asset(m), originalName: m.originalName, used: usedMedia(m.id), usage: Object.values(state.banners).filter(b => b.desktopMediaId === m.id || b.mobileMediaId === m.id).map(b => b.id) })) }));
  app.post('/api/superadmin/media', adminOnly, (req, res) => mediaUpload.single('file')(req, res, err => { if (err) return res.status(err.code === 'LIMIT_FILE_SIZE' ? 413 : 400).json({ error: err.code === 'LIMIT_FILE_SIZE' ? 'MEDIA_TOO_LARGE' : 'UNSUPPORTED_MEDIA' }); if (!req.file) return res.status(400).json({ error: 'MEDIA_REQUIRED' }); if (!mediaSignature(req.file)) { fs.rmSync(req.file.path, { force: true }); return res.status(400).json({ error: 'INVALID_MEDIA_SIGNATURE' }); } const bytes = fs.readFileSync(req.file.path); const dimensions = req.file.mimetype === 'image/png' ? pngDimensions(bytes) : req.file.mimetype === 'image/jpeg' ? jpegDimensions(bytes) : null; if (!dimensions || dimensions.width < 320 || dimensions.height < 80 || dimensions.width > 8000 || dimensions.height > 8000) { fs.rmSync(req.file.path, { force: true }); return res.status(400).json({ error: 'INVALID_MEDIA_DIMENSIONS' }); } const m = { id: id('media'), storageName: path.basename(req.file.path), originalName: str(req.file.originalname, 180), mimeType: req.file.mimetype, bytes: req.file.size, width: dimensions.width, height: dimensions.height, altText: str(req.body?.altText, 180), public: false, uploadedAt: now() }; state.media[m.id] = m; audit(req, 'MEDIA_UPLOADED', { mediaId: m.id, bytes: m.bytes }); res.status(201).json({ media: asset(m) }); }));
  app.put('/api/superadmin/media/:mediaId', adminOnly, (req, res) => { const m = state.media[req.params.mediaId]; if (!m) return res.status(404).json({ error: 'MEDIA_NOT_FOUND' }); if (req.body?.altText !== undefined) m.altText = str(req.body.altText, 180); if (req.body?.public !== undefined) m.public = Boolean(req.body.public); audit(req, 'MEDIA_UPDATED', { mediaId: m.id }); res.json({ media: asset(m) }); });
  app.delete('/api/superadmin/media/:mediaId', adminOnly, (req, res) => { const m = state.media[req.params.mediaId]; if (!m) return res.status(404).json({ error: 'MEDIA_NOT_FOUND' }); if (usedMedia(m.id)) return res.status(409).json({ error: 'MEDIA_IN_USE' }); fs.rmSync(path.join(MEDIA_DIR, m.storageName), { force: true }); delete state.media[m.id]; audit(req, 'MEDIA_DELETED', { mediaId: m.id }); res.status(204).end(); });
  app.get('/api/public/media/:mediaId', (req, res) => { const m = state.media[req.params.mediaId]; if (!m || !m.public || !usedMedia(m.id)) return res.status(404).end(); const file = path.join(MEDIA_DIR, m.storageName); if (!file.startsWith(`${MEDIA_DIR}${path.sep}`) || !fs.existsSync(file)) return res.status(404).end(); res.type(m.mimeType).sendFile(file); });

  app.get('/api/superadmin/banners', adminOnly, (req, res) => res.json({ banners: Object.values(state.banners).sort((a,b) => a.position - b.position || b.priority - a.priority).map(bannerRow) }));
  app.post('/api/superadmin/banners', adminOnly, (req, res) => { const b = req.body || {}; const cta = validUrl(b.destinationUrl); if (cta === null) return res.status(400).json({ error: 'UNSAFE_DESTINATION_URL' }); const start = dateValue(b.startAt) || now(); const end = b.endAt ? dateValue(b.endAt) : null; if (b.endAt && !end || end && Date.parse(end) <= Date.parse(start)) return res.status(400).json({ error: 'INVALID_BANNER_DATES' }); if (!state.media[b.desktopMediaId] || (b.mobileMediaId && !state.media[b.mobileMediaId])) return res.status(400).json({ error: 'BANNER_MEDIA_REQUIRED' }); const idValue = id('banner'); state.banners[idValue] = { id: idValue, title: str(b.title, 120), subtitle: str(b.subtitle, 240), desktopMediaId: b.desktopMediaId, mobileMediaId: b.mobileMediaId || b.desktopMediaId, altText: str(b.altText, 180), ctaLabel: str(b.ctaLabel, 80), destinationUrl: cta, position: Number.isInteger(b.position) ? Math.max(0, b.position) : Object.keys(state.banners).length, priority: Number.isFinite(Number(b.priority)) ? Number(b.priority) : 0, startAt: start, endAt: end, status: status(b.status) || 'DRAFT', createdAt: now(), updatedAt: now() }; audit(req, 'BANNER_CREATED', { bannerId: idValue }); res.status(201).json({ banner: bannerRow(state.banners[idValue]) }); });
  app.put('/api/superadmin/banners/:bannerId', adminOnly, (req, res) => { const b = state.banners[req.params.bannerId]; if (!b) return res.status(404).json({ error: 'BANNER_NOT_FOUND' }); const input = req.body || {}; if (input.destinationUrl !== undefined) { const cta = validUrl(input.destinationUrl); if (cta === null) return res.status(400).json({ error: 'UNSAFE_DESTINATION_URL' }); b.destinationUrl = cta; } for (const k of ['title','subtitle','altText','ctaLabel']) if (input[k] !== undefined) b[k] = str(input[k], k === 'title' ? 120 : 240); for (const k of ['desktopMediaId','mobileMediaId']) if (input[k] !== undefined) { if (!state.media[input[k]]) return res.status(400).json({ error: 'MEDIA_NOT_FOUND' }); b[k] = input[k]; } if (input.status !== undefined && !status(input.status)) return res.status(400).json({ error: 'INVALID_BANNER_STATUS' }); if (input.status !== undefined) b.status = status(input.status); b.updatedAt = now(); audit(req, 'BANNER_UPDATED', { bannerId: b.id }); res.json({ banner: bannerRow(b) }); });
  app.post('/api/superadmin/banners/:bannerId/publish', adminOnly, (req, res) => { const b = state.banners[req.params.bannerId]; if (!b) return res.status(404).json({ error: 'BANNER_NOT_FOUND' }); b.status = 'PUBLISHED'; b.updatedAt = now(); state.media[b.desktopMediaId].public = true; if (state.media[b.mobileMediaId]) state.media[b.mobileMediaId].public = true; audit(req, 'BANNER_PUBLISHED', { bannerId: b.id }); res.json({ banner: bannerRow(b) }); });
  app.post('/api/superadmin/banners/:bannerId/unpublish', adminOnly, (req, res) => { const b = state.banners[req.params.bannerId]; if (!b) return res.status(404).json({ error: 'BANNER_NOT_FOUND' }); b.status = 'UNPUBLISHED'; b.updatedAt = now(); audit(req, 'BANNER_UNPUBLISHED', { bannerId: b.id }); res.json({ banner: bannerRow(b) }); });
  app.post('/api/superadmin/banners/reorder', adminOnly, (req, res) => { const ids = Array.isArray(req.body?.ids) ? req.body.ids : []; ids.forEach((x, i) => { if (state.banners[x]) state.banners[x].position = i; }); audit(req, 'BANNERS_REORDERED', { count: ids.length }); res.json({ banners: Object.values(state.banners).sort((a,b)=>a.position-b.position).map(bannerRow) }); });
  app.delete('/api/superadmin/banners/:bannerId', adminOnly, (req, res) => { if (!state.banners[req.params.bannerId]) return res.status(404).json({ error: 'BANNER_NOT_FOUND' }); delete state.banners[req.params.bannerId]; audit(req, 'BANNER_DELETED', { bannerId: req.params.bannerId }); res.status(204).end(); });
  app.get('/api/public/banners', (req, res) => { const t = Date.now(); const banners = Object.values(state.banners).filter(b => b.status === 'PUBLISHED' && Date.parse(b.startAt) <= t && (!b.endAt || Date.parse(b.endAt) > t)).sort((a,b) => a.position - b.position || b.priority - a.priority).map(b => ({ id:b.id,title:b.title,subtitle:b.subtitle,altText:b.altText,ctaLabel:b.ctaLabel,destinationUrl:b.destinationUrl,desktopUrl:`/api/public/media/${b.desktopMediaId}`,mobileUrl:`/api/public/media/${b.mobileMediaId}` })); res.json({ banners, announcement: state.site.announcement }); });

  function validateCampaign(input, baseAmount, shopId) { const code = normalizeCode(input); if (!code) return { error: 'COUPON_REQUIRED' }; const c = Object.values(state.campaigns).find(x => x.code === code); const t = Date.now(); if (!c || c.status !== 'ACTIVE' || Date.parse(c.startAt) > t || Date.parse(c.endAt) <= t) return { error: 'COUPON_INVALID' }; if (Number(baseAmount) < c.minimumAmount) return { error: 'COUPON_MINIMUM_NOT_MET' }; if (c.shopIds.length && !c.shopIds.includes(shopId)) return { error: 'COUPON_NOT_ELIGIBLE' }; const used = Object.values(state.redemptions).filter(r => r.campaignId === c.id && r.status === 'REDEEMED').length; if (c.totalLimit && used >= c.totalLimit) return { error: 'COUPON_LIMIT_REACHED' }; const discount = c.discountType === 'PERCENTAGE' ? Math.min(Number(baseAmount) * c.discountValue / 100, c.maximumDiscount || Infinity) : c.discountValue; return { campaign: c, discount: money(Math.min(Math.max(0, discount), Number(baseAmount))), finalAmount: money(Math.max(0, Number(baseAmount) - discount)) }; }
  app.post('/api/public/coupons/validate', (req, res) => { const result = validateCampaign(req.body?.code, req.body?.baseAmount, req.body?.shopId); if (result.error) return res.status(400).json({ error: result.error }); res.json({ code: result.campaign.code, discount: result.discount, finalAmount: result.finalAmount, baseAmount: money(req.body.baseAmount) }); });
  app.get('/api/superadmin/campaigns', adminOnly, (req, res) => res.json({ campaigns: Object.values(state.campaigns).map(campaignRow) }));
  app.post('/api/superadmin/campaigns', adminOnly, (req, res) => { const x=req.body||{}, code=normalizeCode(x.code), start=dateValue(x.startAt), end=dateValue(x.endAt); if (!code || state.campaigns[code] || !start || !end || Date.parse(end)<=Date.parse(start)) return res.status(400).json({ error:'INVALID_CAMPAIGN' }); const type=String(x.discountType||'PERCENTAGE').toUpperCase(), value=Number(x.discountValue), cap=Number(x.maximumDiscount||0), minimum=Number(x.minimumAmount||0), limit=Number(x.totalLimit||0); if (!['PERCENTAGE','FIXED'].includes(type) || !Number.isFinite(value) || value<=0 || (type==='PERCENTAGE' && value>100) || (type==='FIXED' && value>100000) || minimum<0 || cap<0 || limit<0) return res.status(400).json({ error:'INVALID_DISCOUNT_RULE' }); const c={id:id('campaign'),code,name:str(x.name,120),description:str(x.description,500),discountType:type,discountValue:money(value),maximumDiscount:cap?money(cap):0,minimumAmount:money(minimum),startAt:start,endAt:end,totalLimit:Math.floor(limit),perCustomerLimit:Math.floor(Number(x.perCustomerLimit||0)),eligibility:String(x.eligibility||'PRINTING'),shopIds:Array.isArray(x.shopIds)?x.shopIds.map(String).slice(0,100):[],status:'ACTIVE',createdAt:now(),updatedAt:now()}; state.campaigns[code]=c; audit(req,'CAMPAIGN_CREATED',{campaignId:c.id,code:c.code}); res.status(201).json({campaign:campaignRow(c)}); });
  app.put('/api/superadmin/campaigns/:campaignId', adminOnly, (req,res)=>{ const c=Object.values(state.campaigns).find(x=>x.id===req.params.campaignId); if(!c)return res.status(404).json({error:'CAMPAIGN_NOT_FOUND'}); if(req.body?.status && !['ACTIVE','PAUSED','EXPIRED','ARCHIVED'].includes(String(req.body.status).toUpperCase()))return res.status(400).json({error:'INVALID_CAMPAIGN_STATUS'}); for(const k of ['name','description','status'])if(req.body[k]!==undefined)c[k]=k==='status'?String(req.body[k]).toUpperCase():str(req.body[k],500); c.updatedAt=now(); audit(req,'CAMPAIGN_UPDATED',{campaignId:c.id}); res.json({campaign:campaignRow(c)}); });
  app.get('/api/superadmin/campaigns/:campaignId/redemptions', adminOnly, (req,res)=>res.json({redemptions:Object.values(state.redemptions).filter(r=>r.campaignId===req.params.campaignId)}));
  app.locals.calculateCoupon = ({ code, baseAmount, shopId }) => { if (!code) return { baseAmount: money(baseAmount), discount: 0, finalAmount: money(baseAmount), campaign: null }; const result=validateCampaign(code,baseAmount,shopId); if(result.error) throw Object.assign(new Error(result.error),{code:result.error}); return result; };
  app.locals.redeemCoupon = order => { if (!order.coupon?.campaignId) return; const existing=state.redemptions[order.coupon.redemptionId]; if(existing?.status==='REDEEMED') return; const c=state.campaigns[order.coupon.campaignCode]; const result=validateCampaign(c?.code,order.originalAmount,order.shopId); if(result.error) throw Error(result.error); const redemption={id:order.coupon.redemptionId,campaignId:c.id,orderId:order.id,discount:order.coupon.discount,status:'REDEEMED',createdAt:now()}; state.redemptions[redemption.id]=redemption; save(); };

  app.get('/api/superadmin/payment-center', adminOnly, (req,res)=>{ const providers=['cashfree','razorpay'].map(p=>({provider:p,environment:p==='cashfree'?(process.env.CASHFREE_ENV||'sandbox'):(process.env.RAZORPAY_ENV||'test'),configured:Boolean(p==='cashfree'?(process.env.CASHFREE_CLIENT_ID&&process.env.CASHFREE_CLIENT_SECRET):(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET)),merchantAccountId:(p==='cashfree'?process.env.CASHFREE_MERCHANT_ACCOUNT_ID:process.env.RAZORPAY_ACCOUNT_ID)||null,secretStorage:'environment-or-external-secret-manager'})); const transactions=[...orders.values()].map(o=>({id:`order_${o.id}`,orderId:o.id,shopId:o.shopId,amount:o.amount,status:o.paymentStatus,method:o.paymentMethod,createdAt:o.createdAt})); res.json({providers,transactions,refunds:[],webhooks:'See verified payment event records; raw payloads are never returned.'}); });
  app.get('/api/superadmin/ai-control', adminOnly, (req,res)=>res.json({config:{...state.ai, apiKeyConfigured:Boolean(process.env.OPENAI_API_KEY||process.env.AI_API_KEY), apiKey:null},usage:[]}));
  app.put('/api/superadmin/ai-control', adminOnly, (req,res)=>{ const x=req.body||{}; if(x.maxOutputTokens!==undefined && (!Number.isInteger(Number(x.maxOutputTokens))||Number(x.maxOutputTokens)<100||Number(x.maxOutputTokens)>4000))return res.status(400).json({error:'INVALID_AI_LIMIT'}); if(x.timeoutMs!==undefined && (!Number.isInteger(Number(x.timeoutMs))||Number(x.timeoutMs)<1000||Number(x.timeoutMs)>60000))return res.status(400).json({error:'INVALID_AI_TIMEOUT'}); for(const k of ['provider','model'])if(x[k]!==undefined)state.ai[k]=str(x[k],120); if(x.enabled!==undefined)state.ai.enabled=Boolean(x.enabled); if(x.maxOutputTokens!==undefined)state.ai.maxOutputTokens=Number(x.maxOutputTokens); if(x.timeoutMs!==undefined)state.ai.timeoutMs=Number(x.timeoutMs); if(x.dailyBudget!==undefined)state.ai.dailyBudget=Math.max(0,Number(x.dailyBudget)||0); state.ai.updatedAt=now(); audit(req,'AI_CONFIG_CHANGED',{enabled:state.ai.enabled,model:state.ai.model}); res.json({config:{...state.ai,apiKeyConfigured:Boolean(process.env.OPENAI_API_KEY||process.env.AI_API_KEY),apiKey:null}}); });
  app.post('/api/superadmin/ai-control/ask', adminOnly, async (req,res)=>{ const question=str(req.body?.question,1000); if(!state.ai.enabled || !(process.env.OPENAI_API_KEY||process.env.AI_API_KEY)) return res.status(503).json({error:'AI_UNCONFIGURED',message:'AI is disabled until a server-side provider and secret are configured.'}); if(!question)return res.status(400).json({error:'QUESTION_REQUIRED'}); const summary={activeShops:Object.values(shops).filter(s=>s.status==='ACTIVE').length,totalOrders:orders.size,completedPrints:[...orders.values()].filter(o=>o.status==='PRINTED').length,failedOrders:[...orders.values()].filter(o=>o.status==='FAILED').length,subscriptionRevenue:0,couponRedemptions:Object.values(state.redemptions).filter(r=>r.status==='REDEEMED').length}; const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),state.ai.timeoutMs); try { const base=process.env.OPENAI_API_BASE||'https://api.openai.com/v1'; const r=await fetch(`${base.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY||process.env.AI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:state.ai.model,messages:[{role:'system',content:'Answer only from this summarized PrinterAuto platform data. Never request or reveal secrets, customer documents, passwords or tokens.'},{role:'user',content:JSON.stringify({question,summary})}],max_tokens:state.ai.maxOutputTokens}),signal:controller.signal}); const d=await r.json().catch(()=>({})); if(!r.ok)throw Error('AI_PROVIDER_ERROR'); audit(req,'AI_QUERY',{model:state.ai.model}); res.json({answer:d.choices?.[0]?.message?.content||'No answer returned.',summary}); } catch(e) { state.ai.lastError='AI provider unavailable'; save(); res.status(502).json({error:'AI_PROVIDER_UNAVAILABLE'}); } finally { clearTimeout(timer); } });

  function analytics(from,to) { const start=from?Date.parse(from):Date.now()-30*86400000, end=to?Date.parse(to)+86400000:Date.now()+86400000; const list=[...orders.values()].filter(o=>Date.parse(o.createdAt)>=start&&Date.parse(o.createdAt)<end); const paid=list.filter(o=>o.paymentStatus==='PAID'); const rows={orders:list.length,completedPrintJobs:list.filter(o=>o.status==='PRINTED').length,failedPrintJobs:list.filter(o=>o.status==='FAILED').length,totalPages:list.reduce((n,o)=>n+(Number(o.pageCount)||0)*(Number(o.copies)||0),0),shopPrintSales:paid.reduce((n,o)=>n+Number(o.amount||0),0),pendingPayments:list.filter(o=>['PAYMENT_PENDING','CASH_PENDING'].includes(o.paymentStatus)).length,paidOrders:paid.length,couponRedemptions:Object.values(state.redemptions).filter(r=>r.status==='REDEEMED'&&Date.parse(r.createdAt)>=start&&Date.parse(r.createdAt)<end).length}; rows.printFailureRate=list.length?Math.round(rows.failedPrintJobs/list.length*10000)/100:0; return rows; }
  app.get('/api/superadmin/bi', adminOnly, (req,res)=>res.json({from:req.query.from||null,to:req.query.to||null,metrics:analytics(req.query.from,req.query.to),campaigns:Object.values(state.campaigns).map(campaignRow),availability:'local-persistence'}));
  app.get('/api/superadmin/bi/export', adminOnly, (req,res)=>{ const m=analytics(req.query.from,req.query.to); res.type('text/csv').send(['metric,value',...Object.entries(m).map(([k,v])=>`${safeCsv(k)},${safeCsv(v)}`)].join('\n')); });
  app.get('/api/superadmin/notifications', adminOnly, (req,res)=>res.json({notifications:state.notifications}));
  app.post('/api/superadmin/notifications', adminOnly, (req,res)=>{ const n={id:id('notice'),severity:['INFO','WARNING','ERROR'].includes(req.body?.severity)?req.body.severity:'INFO',message:str(req.body?.message,500),createdAt:now(),read:false}; if(!n.message)return res.status(400).json({error:'MESSAGE_REQUIRED'}); state.notifications.unshift(n); audit(req,'NOTIFICATION_CREATED',{notificationId:n.id}); res.status(201).json({notification:n}); });
  app.get('/api/public/content', (req,res)=>res.json({site:{platformName:state.site.platformName,announcement:state.site.announcement,logoUrl:state.site.logoMediaId?`/api/public/media/${state.site.logoMediaId}`:null,privacyPolicy:state.site.privacyPolicy,terms:state.site.terms,refundPolicy:state.site.refundPolicy,helpContent:state.site.helpContent},banners:Object.values(state.banners).filter(b=>b.status==='PUBLISHED'&&Date.parse(b.startAt)<=Date.now()&&(!b.endAt||Date.parse(b.endAt)>Date.now())).sort((a,b)=>a.position-b.position).map(b=>({id:b.id,title:b.title,subtitle:b.subtitle,altText:b.altText,ctaLabel:b.ctaLabel,destinationUrl:b.destinationUrl,desktopUrl:`/api/public/media/${b.desktopMediaId}`,mobileUrl:`/api/public/media/${b.mobileMediaId}`}))}));
  const expire = () => { let changed=false; for(const b of Object.values(state.banners)) if(b.status==='PUBLISHED'&&b.endAt&&Date.parse(b.endAt)<=Date.now()){b.status='EXPIRED';changed=true;} for(const c of Object.values(state.campaigns)) if(c.status==='ACTIVE'&&Date.parse(c.endAt)<=Date.now()){c.status='EXPIRED';changed=true;} if(changed)save(); }; setInterval(expire,60000).unref();
};
