const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

module.exports = function registerPhase3(ctx) {
  const { app, ROOT, shops, shopUsers, printers, orders, activityLogs, id, now, hashPassword, verifyPassword, publicShop, publicOrder, publicPrinter, persist } = ctx;
  const DATA = path.join(ROOT, 'storage', 'phase3-data.json');
  const sessions = new Map();
  const state = { plans: {}, subscriptions: {}, payments: [], audit: [], settings: { platformName: 'Printer Auto', supportContact: 'support@example.local', maintenanceMode: false, fileRetentionMinutes: 5, paymentGateway: 'NOT_CONFIGURED' }, health: [] };
  const defaultPlans = [
    { id: 'basic', name: 'Basic', price: 299, duration: 'MONTH', features: ['Customer printing', 'Shopkeeper panel'], status: 'ACTIVE' },
    { id: 'pro', name: 'Pro', price: 599, duration: 'MONTH', features: ['Everything in Basic', 'Reports', 'Priority support'], status: 'ACTIVE' },
    { id: 'business', name: 'Business', price: 999, duration: 'MONTH', features: ['Everything in Pro', 'Advanced analytics'], status: 'ACTIVE' }
  ];
  function save() { fs.mkdirSync(path.dirname(DATA), { recursive: true }); fs.writeFileSync(DATA, JSON.stringify(state, null, 2)); }
  try { Object.assign(state, JSON.parse(fs.readFileSync(DATA, 'utf8'))); } catch {}
  if (!Object.keys(state.plans).length) for (const p of defaultPlans) state.plans[p.id] = p;
  for (const shop of Object.values(shops)) {
    shop.status = shop.status || (shop.active === false ? 'SUSPENDED' : 'ACTIVE');
    shop.active = shop.status === 'ACTIVE';
    if (!state.subscriptions[shop.id]) state.subscriptions[shop.id] = { id: id('sub'), shopId: shop.id, planId: 'basic', status: 'TRIAL', startDate: now(), endDate: new Date(Date.now() + 14 * 86400000).toISOString(), amount: 0, paymentStatus: 'PENDING' };
  }
  save();
  function refreshAccess() {
    for (const sub of Object.values(state.subscriptions)) {
      if (new Date(sub.endDate) < new Date() && ['ACTIVE', 'TRIAL'].includes(sub.status)) sub.status = 'EXPIRED';
    }
    app.locals.platformMaintenance = Boolean(state.settings.maintenanceMode);
    app.locals.shopBlocked = shopId => { const shop = shops[shopId]; const sub = state.subscriptions[shopId]; return Boolean(app.locals.platformMaintenance || !shop || shop.status !== 'ACTIVE' || shop.active === false || ['EXPIRED', 'CANCELLED'].includes(sub?.status)); };
    app.locals.shopkeeperBlocked = shopId => { const sub = state.subscriptions[shopId]; return Boolean(app.locals.platformMaintenance || app.locals.shopBlocked(shopId)); };
  }
  refreshAccess();
  setInterval(refreshAccess, 60_000).unref();

  function cookies(req) { return Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(v => { const i = v.indexOf('='); return [v.slice(0, i).trim(), decodeURIComponent(v.slice(i + 1))]; })); }
  function adminUser() { return state.admin; }
  if (!state.admin) { const p = hashPassword(process.env.SUPERADMIN_PASSWORD || 'Admin123!'); state.admin = { id: 'admin_primary', identifier: process.env.SUPERADMIN_IDENTIFIER || 'admin@printerauto.local', role: 'SUPER_ADMIN', salt: p.salt, hash: p.hash, status: 'ACTIVE', lastLogin: null }; save(); }
  function adminAuth(req, res, next) { const token = cookies(req).superadmin_session; const session = token && sessions.get(token); if (!session || session.expiresAt < Date.now() || !state.admin || state.admin.status !== 'ACTIVE') return res.status(401).json({ error: 'SUPERADMIN_UNAUTHORIZED' }); req.superAdmin = state.admin; next(); }
  function adminLog(req, action, metadata = {}) { const entry = { id: id('audit'), action, adminId: req.superAdmin?.id || state.admin.id, at: now(), metadata }; state.audit.push(entry); if (state.audit.length > 5000) state.audit.shift(); save(); }
  function shopRows() { return Object.values(shops).map(shop => { const list = [...orders.values()].filter(o => o.shopId === shop.id); const subscription = state.subscriptions[shop.id]; const ps = [...printers.values()].filter(p => p.shopId === shop.id); return { ...publicShop(shop), ownerName: shop.ownerName, mobile: shop.mobile, email: shop.email, status: shop.status, subscription, orders: list.length, revenue: list.filter(o => o.paymentStatus === 'PAID').reduce((s, o) => s + o.amount, 0), printersOnline: ps.filter(p => p.status === 'Online' || p.status === 'Busy').length, printersTotal: ps.length, createdAt: shop.createdAt || shop.createdAt || null }; }); }
  function allStats() { const list = [...orders.values()]; const today = new Date().toISOString().slice(0, 10); const todayList = list.filter(o => o.createdAt.slice(0, 10) === today); const subs = Object.values(state.subscriptions); const paidSubs = state.payments.filter(p => p.status === 'PAID'); const shopRevenue = list.filter(o => o.paymentStatus === 'PAID').reduce((s, o) => s + o.amount, 0); const platformRevenue = paidSubs.reduce((s, p) => s + p.amount, 0); const ps = [...printers.values()]; return { today: { totalShops: Object.keys(shops).length, activeShops: Object.values(shops).filter(s => s.status === 'ACTIVE').length, newShops: Object.values(shops).filter(s => s.createdAt?.slice(0, 10) === today).length, totalOrders: todayList.length, totalPrints: todayList.filter(o => o.status === 'PRINTED').length, totalPages: todayList.reduce((s, o) => s + o.pageCount * o.copies, 0), onlinePayments: todayList.filter(o => o.paymentMethod === 'online' && o.paymentStatus === 'PAID').reduce((s, o) => s + o.amount, 0), cashPayments: todayList.filter(o => o.paymentMethod === 'cash' && o.paymentStatus === 'PAID').reduce((s, o) => s + o.amount, 0), platformRevenue, failedJobs: todayList.filter(o => o.status === 'FAILED').length }, overall: { activeSubscriptions: subs.filter(s => s.status === 'ACTIVE').length, expiredSubscriptions: subs.filter(s => s.status === 'EXPIRED').length, trialShops: subs.filter(s => s.status === 'TRIAL').length, totalRegisteredShops: Object.keys(shops).length, onlinePrinters: ps.filter(p => ['Online', 'Busy'].includes(p.status)).length, offlinePrinters: ps.filter(p => ['Offline', 'Error'].includes(p.status)).length, failedPrintJobs: list.filter(o => o.status === 'FAILED').length }, shopRevenue, platformRevenue, totalOrders: list.length }; }
  function health() { const tmp = path.join(ROOT, 'storage', 'tmp'); let usage = 0; try { usage = fs.readdirSync(tmp).reduce((s, f) => { try { return s + fs.statSync(path.join(tmp, f)).size; } catch { return s; } }, 0); } catch {} const ps = [...printers.values()]; const h = { checkedAt: now(), backend: { status: 'HEALTHY', responseTime: 1 }, database: { status: 'WARNING', connection: 'LOCAL_FALLBACK', responseTime: 1, errorCount: 0 }, storage: { status: 'HEALTHY', usageBytes: usage, available: 'configured filesystem' }, payment: { status: 'WARNING', gateway: 'NOT_CONFIGURED', recentFailures: 0 }, print: { status: ps.some(p => ['Offline', 'Error'].includes(p.status)) ? 'WARNING' : 'HEALTHY', onlineConnectors: ps.filter(p => ['Online', 'Busy'].includes(p.status)).length, offlineConnectors: ps.filter(p => ['Offline', 'Error'].includes(p.status)).length, failedJobs: [...orders.values()].filter(o => o.status === 'FAILED').length, queueSize: [...orders.values()].filter(o => ['PAID', 'PRINT_QUEUED', 'PRINTING'].includes(o.status)).length }, api: { status: 'HEALTHY', errorRate: 0, responseTime: 1 } }; state.health.unshift(h); state.health = state.health.slice(0, 100); save(); return h; }
  function subscriptionRow(s) { return { ...s, shop: shops[s.shopId]?.name || s.shopId, plan: state.plans[s.planId] || null }; }

  app.post('/api/superadmin/login', (req, res) => { const identifier = String(req.body?.identifier || '').trim().toLowerCase(); const password = String(req.body?.password || ''); const a = state.admin; if (!a || a.status !== 'ACTIVE' || identifier !== a.identifier.toLowerCase() || !verifyPassword(password, a)) return res.status(401).json({ error: 'INVALID_CREDENTIALS' }); const token = crypto.randomBytes(32).toString('hex'); sessions.set(token, { adminId: a.id, expiresAt: Date.now() + 8 * 3600000 }); a.lastLogin = now(); adminLog({ superAdmin: a }, 'SUPER_ADMIN_LOGIN'); const secure = process.env.NODE_ENV === 'production' ? '; Secure' : ''; res.setHeader('Set-Cookie', `superadmin_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800${secure}`); res.json({ user: { id: a.id, identifier: a.identifier, role: a.role } }); });
  app.post('/api/superadmin/logout', adminAuth, (req, res) => { sessions.delete(cookies(req).superadmin_session); adminLog(req, 'SUPER_ADMIN_LOGOUT'); res.setHeader('Set-Cookie', 'superadmin_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); res.status(204).end(); });
  app.get('/api/superadmin/me', adminAuth, (req, res) => res.json({ user: { id: req.superAdmin.id, identifier: req.superAdmin.identifier, role: req.superAdmin.role } }));
  app.get('/api/superadmin/dashboard', adminAuth, (req, res) => res.json({ stats: allStats(), charts: chartData(), health: health(), notifications: notifications() }));
  app.get('/api/superadmin/shops', adminAuth, (req, res) => res.json({ shops: shopRows() }));
  app.get('/api/superadmin/shops/:shopId', adminAuth, (req, res) => { const s = shops[req.params.shopId]; if (!s) return res.status(404).json({ error: 'SHOP_NOT_FOUND' }); res.json({ shop: shopRows().find(x => x.id === s.id), orders: [...orders.values()].filter(o => o.shopId === s.id).map(publicOrder), subscription: subscriptionRow(state.subscriptions[s.id]) }); });
  app.post('/api/superadmin/shops/:shopId/status', adminAuth, (req, res) => { const s = shops[req.params.shopId]; const status = String(req.body?.status || '').toUpperCase(); if (!s || !['ACTIVE', 'SUSPENDED', 'EXPIRED'].includes(status)) return res.status(400).json({ error: 'INVALID_SHOP_STATUS' }); s.status = status; s.active = status === 'ACTIVE'; refreshAccess(); adminLog(req, 'SHOP_STATUS_CHANGED', { shopId: s.id, status }); persist(); res.json({ shop: publicShop(s), status: s.status }); });
  app.get('/api/superadmin/shopkeepers', adminAuth, (req, res) => res.json({ shopkeepers: [...shopUsers.values()].map(u => ({ id: u.id, identifier: u.identifier, shopId: u.shopId, shop: shops[u.shopId]?.name, role: u.role || 'SHOPKEEPER', status: u.status || 'ACTIVE', lastLogin: u.lastLogin || null, subscription: state.subscriptions[u.shopId]?.status })) }));
  app.post('/api/superadmin/shopkeepers/:userId/status', adminAuth, (req, res) => { const u = shopUsers.get(req.params.userId); const status = String(req.body?.status || '').toUpperCase(); if (!u || !['ACTIVE', 'SUSPENDED'].includes(status)) return res.status(400).json({ error: 'INVALID_USER_STATUS' }); u.status = status; adminLog(req, 'SHOPKEEPER_STATUS_CHANGED', { userId: u.id, status }); persist(); res.json({ ok: true, status }); });
  app.get('/api/superadmin/plans', adminAuth, (req, res) => res.json({ plans: Object.values(state.plans) }));
  app.post('/api/superadmin/plans', adminAuth, (req, res) => { const plan = { id: String(req.body?.id || id('plan')).toLowerCase().replace(/[^a-z0-9_-]/g, ''), name: String(req.body?.name || 'New plan').slice(0, 80), price: Number(req.body?.price || 0), duration: String(req.body?.duration || 'MONTH'), features: Array.isArray(req.body?.features) ? req.body.features.slice(0, 20) : [], status: 'ACTIVE' }; if (!plan.id || !Number.isFinite(plan.price) || plan.price < 0) return res.status(400).json({ error: 'INVALID_PLAN' }); state.plans[plan.id] = plan; adminLog(req, 'PLAN_CREATED', { planId: plan.id }); res.status(201).json({ plan }); });
  app.put('/api/superadmin/plans/:planId', adminAuth, (req, res) => { const p = state.plans[req.params.planId]; if (!p) return res.status(404).json({ error: 'PLAN_NOT_FOUND' }); for (const k of ['name', 'duration', 'status']) if (req.body?.[k] !== undefined) p[k] = String(req.body[k]); if (req.body?.price !== undefined) p.price = Number(req.body.price); if (Array.isArray(req.body?.features)) p.features = req.body.features.slice(0, 20); adminLog(req, 'PLAN_UPDATED', { planId: p.id }); res.json({ plan: p }); });
  app.get('/api/superadmin/subscriptions', adminAuth, (req, res) => res.json({ subscriptions: Object.values(state.subscriptions).map(subscriptionRow) }));
  app.post('/api/superadmin/subscriptions/:subscriptionId/action', adminAuth, (req, res) => { const s = Object.values(state.subscriptions).find(x => x.id === req.params.subscriptionId); const action = String(req.body?.action || ''); if (!s || !['extend', 'activate', 'cancel'].includes(action)) return res.status(400).json({ error: 'INVALID_SUBSCRIPTION_ACTION' }); if (action === 'extend') s.endDate = new Date(new Date(s.endDate).getTime() + 30 * 86400000).toISOString(); if (action === 'activate') s.status = 'ACTIVE'; if (action === 'cancel') s.status = 'CANCELLED'; adminLog(req, 'SUBSCRIPTION_ACTION', { subscriptionId: s.id, action }); res.json({ subscription: subscriptionRow(s) }); });
  app.get('/api/superadmin/orders', adminAuth, (req, res) => res.json({ orders: [...orders.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(o => ({ ...publicOrder(o), shopName: shops[o.shopId]?.name })) }));
  app.get('/api/superadmin/payments', adminAuth, (req, res) => res.json({ payments: [...state.payments, ...[...orders.values()].filter(o => o.paymentStatus !== 'PAYMENT_PENDING').map(o => ({ id: `order_${o.id}`, shopId: o.shopId, orderId: o.id, method: o.paymentMethod, amount: o.amount, status: o.paymentStatus, createdAt: o.createdAt }))] }));
  app.get('/api/superadmin/revenue', adminAuth, (req, res) => { const stats = allStats(); const report = { subscriptionRevenue: state.payments.filter(p => p.status === 'PAID').reduce((s, p) => s + p.amount, 0), otherPlatformRevenue: 0, total: stats.platformRevenue, successfulPayments: state.payments.filter(p => p.status === 'PAID').length, failedPayments: state.payments.filter(p => p.status === 'FAILED').length, refunds: state.payments.filter(p => p.status === 'REFUNDED').reduce((s, p) => s + p.amount, 0) }; if (req.query.format === 'csv') return res.type('text/csv').send(['metric,value', ...Object.entries(report).map(([k, v]) => `${k},${v}`)].join('\n')); res.json({ report }); });
  app.get('/api/superadmin/printers', adminAuth, (req, res) => res.json({ printers: [...printers.values()].map(p => ({ ...publicPrinter(p), shopName: shops[p.shopId]?.name, connector: p.type, lastHeartbeat: p.lastSeen })) }));
  app.get('/api/superadmin/health', adminAuth, (req, res) => res.json({ health: health() }));
  app.get('/api/superadmin/reports', adminAuth, (req, res) => { const list = [...orders.values()]; const report = { shops: shopRows(), totalOrders: list.length, totalPrints: list.filter(o => o.status === 'PRINTED').length, totalPages: list.reduce((s, o) => s + o.pageCount * o.copies, 0), shopRevenue: list.filter(o => o.paymentStatus === 'PAID').reduce((s, o) => s + o.amount, 0), subscriptionRevenue: state.payments.filter(p => p.status === 'PAID').reduce((s, p) => s + p.amount, 0), topShops: shopRows().sort((a, b) => b.orders - a.orders).slice(0, 5) }; if (req.query.format === 'csv') return res.type('text/csv').send(['shop,orders,revenue,status', ...report.shops.map(s => `${s.name},${s.orders},${s.revenue},${s.status}`)].join('\n')); res.json({ report }); });
  app.get('/api/superadmin/audit', adminAuth, (req, res) => res.json({ audit: state.audit.concat(activityLogs.map(x => ({ ...x, source: 'SHOPKEEPER' }))).sort((a, b) => String(b.at || b.createdAt).localeCompare(String(a.at || a.createdAt))).slice(0, 300) }));
  app.get('/api/superadmin/settings', adminAuth, (req, res) => res.json({ settings: { ...state.settings, paymentGateway: state.settings.paymentGateway === 'NOT_CONFIGURED' ? 'NOT_CONFIGURED' : 'CONFIGURED' } }));
  app.put('/api/superadmin/settings', adminAuth, (req, res) => { for (const k of ['platformName', 'supportContact', 'fileRetentionMinutes']) if (req.body?.[k] !== undefined) state.settings[k] = k === 'fileRetentionMinutes' ? Math.max(1, Number(req.body[k])) : String(req.body[k]).slice(0, 160); adminLog(req, 'PLATFORM_SETTINGS_CHANGED'); res.json({ settings: state.settings }); });
  app.post('/api/superadmin/maintenance', adminAuth, (req, res) => { state.settings.maintenanceMode = Boolean(req.body?.enabled); refreshAccess(); adminLog(req, 'MAINTENANCE_MODE_CHANGED', { enabled: state.settings.maintenanceMode }); res.json({ maintenanceMode: state.settings.maintenanceMode }); });
  app.post('/api/superadmin/ai', adminAuth, (req, res) => { const message = String(req.body?.message || '').trim(); const confirm = req.body?.confirm === true; const action = req.body?.action; const stats = allStats(); let result = ''; let suggestedAction = null;
  if (action && !confirm) { result = `This action needs confirmation before it can run: ${action}.`; suggestedAction = action; }
  else if (action && confirm && ['SUSPEND_SHOP', 'ACTIVATE_SHOP', 'EXTEND_SUBSCRIPTION'].includes(action)) { const shopId = String(req.body.shopId || ''); if (action === 'SUSPEND_SHOP' || action === 'ACTIVATE_SHOP') { const s = shops[shopId]; if (!s) return res.status(404).json({ error: 'SHOP_NOT_FOUND' }); s.status = action === 'SUSPEND_SHOP' ? 'SUSPENDED' : 'ACTIVE'; s.active = s.status === 'ACTIVE'; persist(); result = `${action === 'SUSPEND_SHOP' ? 'Suspended' : 'Activated'} ${s.name}.`; } else result = 'Subscription extension requires a selected subscription and is ready for the confirmation workflow.'; adminLog(req, 'AI_ACTION', { request: message, action, confirmation: 'YES', result }); }
  else if (/offline|printer/i.test(message)) result = `There are ${stats.overall.offlinePrinters} offline connectors and ${stats.overall.onlinePrinters} online connectors.`; else if (/revenue|कमाई|कमाई/i.test(message)) result = `Platform revenue is ₹${stats.platformRevenue.toFixed(2)}. Shop print sales are tracked separately at ₹${stats.shopRevenue.toFixed(2)}.`; else if (/order|ऑर्डर/i.test(message)) result = `There have been ${stats.totalOrders} orders in the current local dataset.`; else if (/shop|दुकान/i.test(message)) result = `${stats.today.activeShops} active shops out of ${stats.overall.totalRegisteredShops} registered shops.`; else if (action && !confirm) { result = `This action needs confirmation before it can run: ${action}.`; suggestedAction = action; } else if (action && confirm && ['SUSPEND_SHOP', 'ACTIVATE_SHOP', 'EXTEND_SUBSCRIPTION'].includes(action)) { const shopId = String(req.body.shopId || ''); if (action === 'SUSPEND_SHOP' || action === 'ACTIVATE_SHOP') { const s = shops[shopId]; if (!s) return res.status(404).json({ error: 'SHOP_NOT_FOUND' }); s.status = action === 'SUSPEND_SHOP' ? 'SUSPENDED' : 'ACTIVE'; s.active = s.status === 'ACTIVE'; persist(); result = `${action === 'SUSPEND_SHOP' ? 'Suspended' : 'Activated'} ${s.name}.`; } else result = 'Subscription extension requires a selected subscription and is ready for the confirmation workflow.'; adminLog(req, 'AI_ACTION', { request: message, action, confirmation: 'YES', result }); } else result = 'I can read dashboard, shop, order, revenue and health data. For changes, ask me to propose an action and confirm it explicitly.'; if (!confirm && action) adminLog(req, 'AI_ACTION_PROPOSED', { request: message, action, confirmation: 'PENDING', result }); res.json({ result, suggestedAction, confirmationRequired: Boolean(suggestedAction) }); });

  function chartData() { const labels = []; const dailyOrders = []; const dailyRevenue = []; for (let i = 6; i >= 0; i--) { const d = new Date(Date.now() - i * 86400000).toISOString().slice(0, 10); const list = [...orders.values()].filter(o => o.createdAt.slice(0, 10) === d); labels.push(d.slice(5)); dailyOrders.push(list.length); dailyRevenue.push(list.filter(o => o.paymentStatus === 'PAID').reduce((s, o) => s + o.amount, 0)); } return { labels, dailyOrders, dailyRevenue, monthlyRevenue: [0, 0, 0, 0, 0, 0, allStats().platformRevenue] }; }
  function notifications() { const n = []; for (const s of Object.values(state.subscriptions)) { const days = Math.ceil((new Date(s.endDate) - Date.now()) / 86400000); if (days <= 3 && days >= 0) n.push({ type: 'SUBSCRIPTION_EXPIRING', shopId: s.shopId, message: `${shops[s.shopId]?.name} subscription expires in ${days} days.` }); } for (const p of printers.values()) if (['Offline', 'Error'].includes(p.status)) n.push({ type: 'PRINTER_OFFLINE', shopId: p.shopId, message: `${shops[p.shopId]?.name} has an offline printer.` }); return n; }
};
