const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

module.exports = function registerPhase4(ctx) {
  const { app, ROOT, shops, shopUsers, printers, orders, uploads, id, now, persist, logActivity, queuePaidOrder, auth } = ctx;
  const DATA = path.join(ROOT, 'storage', 'phase4-data.json');
  const state = { connections: {}, webhooks: {}, paymentEvents: {}, printJobs: {}, connectors: {}, processing: {}, cleanup: {}, providerStats: { cashfree: { successes: 0, failures: 0 }, razorpay: { successes: 0, failures: 0 } } };
  try { Object.assign(state, JSON.parse(fs.readFileSync(DATA, 'utf8'))); } catch {}
  const save = () => { fs.mkdirSync(path.dirname(DATA), { recursive: true }); fs.writeFileSync(DATA, JSON.stringify(state, null, 2)); };
  const hash = (secret, value) => crypto.createHmac('sha256', secret || '').update(value).digest('hex');
  const providerConfig = { cashfree: { secret: process.env.CASHFREE_CLIENT_SECRET || process.env.PLATFORM_CASHFREE_CLIENT_SECRET || process.env.PAYMENT_WEBHOOK_SECRET, configured: Boolean(process.env.CASHFREE_CLIENT_ID || process.env.PLATFORM_CASHFREE_CLIENT_ID), mode: process.env.CASHFREE_ENV || 'sandbox' }, razorpay: { secret: process.env.RAZORPAY_KEY_SECRET || process.env.PLATFORM_RAZORPAY_KEY_SECRET || process.env.PAYMENT_WEBHOOK_SECRET, configured: Boolean(process.env.RAZORPAY_KEY_ID || process.env.PLATFORM_RAZORPAY_KEY_ID), mode: process.env.RAZORPAY_ENV || 'test' } };
  const adapters = {
    cashfree: { name: 'Cashfree', start: (order, connection) => ({ provider: 'cashfree', status: 'PENDING', orderId: order.id, amount: order.amount, merchantAccountId: connection.merchantAccountId, mode: providerConfig.cashfree.mode, message: providerConfig.cashfree.configured ? 'Cashfree sandbox order session must be created with the server credential.' : 'Cashfree is not configured on this server.' }), verify: (payload, signature) => providerConfig.cashfree.secret && signature && crypto.timingSafeEqual(Buffer.from(hash(providerConfig.cashfree.secret, payload)), Buffer.from(String(signature))) },
    razorpay: { name: 'Razorpay', start: (order, connection) => ({ provider: 'razorpay', status: 'PENDING', orderId: order.id, amount: order.amount, merchantAccountId: connection.merchantAccountId, mode: providerConfig.razorpay.mode, message: providerConfig.razorpay.configured ? 'Razorpay test order must be created with the server credential.' : 'Razorpay is not configured on this server.' }), verify: (payload, signature) => providerConfig.razorpay.secret && signature && crypto.timingSafeEqual(Buffer.from(hash(providerConfig.razorpay.secret, payload)), Buffer.from(String(signature))) }
  };
  function safeProvider(p) { return { provider: p, name: adapters[p]?.name, configured: providerConfig[p]?.configured || false, mode: providerConfig[p]?.mode, officialConnectionFlow: p === 'cashfree' ? 'Cashfree merchant/partner onboarding is required; no client secret is accepted from Shopkeeper.' : 'Razorpay Route/Partner onboarding is required; no key secret is accepted from Shopkeeper.' }; }
  function own(req, shopId) { return req.shopkeeper?.shopId === shopId; }
  function shopAuth(req, res, next) { return auth(req, res, next); }
  function audit(req, action, metadata = {}) { if (req.shopkeeper) logActivity(req.shopkeeper, action, metadata); }
  function connectionFor(shopId) { return state.connections[shopId] || null; }
  function connectorFor(shopId) { return Object.values(state.connectors).find(c => c.shopId === shopId && c.status === 'ONLINE') || null; }
  function customerError(code) { return code === 'PAYMENT_NOT_VERIFIED' ? 'Payment verify नहीं हो पाया। कृपया दोबारा कोशिश करें।' : 'Payment service temporarily unavailable. Please try again.'; }

  // Shopkeeper payment connection: onboarding is deliberately not faked.
  app.get('/api/shopkeeper/payment', shopAuth, (req, res) => res.json({ providers: Object.keys(adapters).map(safeProvider), connection: connectionFor(req.shopkeeper.shopId) ? { ...connectionFor(req.shopkeeper.shopId), secret: undefined } : null }));
  app.post('/api/shopkeeper/payment/connect', shopAuth, (req, res) => { const provider = String(req.body?.provider || '').toLowerCase(); if (!adapters[provider]) return res.status(400).json({ error: 'UNSUPPORTED_PROVIDER' }); if (!providerConfig[provider].configured) return res.status(503).json({ error: 'PROVIDER_NOT_CONFIGURED', message: `${adapters[provider].name} official onboarding cannot start until platform credentials are configured.` }); const onboardingId = id('onboard'); state.connections[req.shopkeeper.shopId] = { shopId: req.shopkeeper.shopId, provider, status: 'ONBOARDING', onboardingId, merchantAccountId: null, createdAt: now(), updatedAt: now() }; save(); audit(req, 'PAYMENT_CONNECTION_STARTED', { provider, onboardingId }); res.status(202).json({ status: 'ONBOARDING', provider, onboardingId, message: 'Continue through the provider’s official merchant onboarding callback; no secret key is collected here.' }); });
  app.post('/api/shopkeeper/payment/callback', shopAuth, (req, res) => { const c = connectionFor(req.shopkeeper.shopId); if (!c || c.status !== 'ONBOARDING' || req.body?.onboardingId !== c.onboardingId) return res.status(400).json({ error: 'INVALID_ONBOARDING_CALLBACK' }); if (!req.body?.merchantAccountId || req.body?.verified !== true) return res.status(400).json({ error: 'PROVIDER_VERIFICATION_REQUIRED' }); c.merchantAccountId = String(req.body.merchantAccountId).slice(0, 160); c.status = 'CONNECTED'; c.updatedAt = now(); save(); audit(req, 'PAYMENT_CONNECTION_VERIFIED', { provider: c.provider }); res.json({ connection: { ...c, merchantAccountId: c.merchantAccountId } }); });
  app.post('/api/shopkeeper/payment/disconnect', shopAuth, (req, res) => { const c = connectionFor(req.shopkeeper.shopId); if (!c) return res.status(404).json({ error: 'NO_PAYMENT_CONNECTION' }); c.status = 'DISCONNECTED'; c.updatedAt = now(); save(); audit(req, 'PAYMENT_CONNECTION_DISCONNECTED', { provider: c.provider }); res.json({ status: c.status }); });
  app.get('/api/shopkeeper/payment/history', shopAuth, (req, res) => res.json({ payments: Object.values(state.paymentEvents).filter(x => x.shopId === req.shopkeeper.shopId).map(x => ({ ...x, raw: undefined })) }));

  // Customer obtains a provider-neutral payment session; provider is selected by the shop connection.
  app.post('/api/orders/:orderId/payment-session', async (req, res) => { const order = orders.get(req.params.orderId); if (!order || order.paymentMethod !== 'online') return res.status(400).json({ error: 'INVALID_ONLINE_ORDER' }); const c = connectionFor(order.shopId); if (!c || c.status !== 'CONNECTED' || !adapters[c.provider]) return res.status(503).json({ error: 'SHOP_PAYMENT_NOT_CONNECTED', message: 'This shop has not connected an online payment provider.' }); const session = adapters[c.provider].start(order, c); order.paymentSession = session; order.updatedAt = now(); state.paymentEvents[id('pay')] = { shopId: order.shopId, orderId: order.id, provider: c.provider, status: 'PENDING', amount: order.amount, createdAt: now() }; save(); res.status(201).json({ payment: session, redirectRequired: true }); });

  // Webhooks verify HMAC over the raw request body and are idempotent by event/payment ID.
  app.post('/api/webhooks/:provider', async (req, res) => { const provider = String(req.params.provider).toLowerCase(); const adapter = adapters[provider]; if (!adapter) return res.status(404).json({ error: 'UNSUPPORTED_PROVIDER' }); const payload = req.rawBody || Buffer.from(JSON.stringify(req.body || {})); const signature = req.headers['x-webhook-signature'] || req.headers['x-razorpay-signature'] || req.headers['x-cashfree-signature']; let verified = false; try { verified = Boolean(adapter.verify(payload, signature)); } catch {} if (!verified) { state.providerStats[provider].failures++; save(); return res.status(401).json({ error: 'INVALID_WEBHOOK_SIGNATURE' }); } const body = req.body || {}; const eventId = String(body.eventId || body.id || body.payment_id || body.razorpay_payment_id || ''); if (!eventId) return res.status(400).json({ error: 'WEBHOOK_ID_REQUIRED' }); if (state.webhooks[eventId]) return res.json({ ok: true, duplicate: true }); state.webhooks[eventId] = { provider, receivedAt: now() }; const order = orders.get(String(body.orderId || body.order_id || body.notes?.orderId || '')); const paid = String(body.status || body.payment_status || '').toUpperCase() === 'PAID' || String(body.event || '').toLowerCase().includes('captured') || String(body.event || '').toLowerCase().includes('success'); if (order && paid && Number(body.amount ?? order.amount) === Number(order.amount)) { order.paymentStatus = 'PAID'; order.status = 'PAID'; order.updatedAt = now(); order.message = 'Payment verified by provider webhook.'; state.providerStats[provider].successes++; state.paymentEvents[eventId] = { id: eventId, shopId: order.shopId, orderId: order.id, provider, amount: order.amount, status: 'PAID', createdAt: now() }; await queuePaidOrder(order, null); } else if (order) { order.message = Number(body.amount ?? order.amount) !== Number(order.amount) ? 'Payment amount mismatch; manual review required.' : 'Payment is pending or failed.'; state.paymentEvents[eventId] = { id: eventId, shopId: order.shopId, orderId: order.id, provider, amount: body.amount, status: 'FAILED', createdAt: now() }; } save(); res.json({ ok: true, verified: true, orderStatus: order?.status || 'UNMATCHED' }); });

  // Production connector registration, pairing, scoped job polling and completion.
  app.post('/api/shopkeeper/connectors/pair', shopAuth, (req, res) => { const code = String(Math.floor(100000 + Math.random() * 900000)); const pairingId = id('pair'); state.connectors[pairingId] = { id: pairingId, shopId: req.shopkeeper.shopId, pairingCode: code, status: 'PAIRING', createdAt: now(), updatedAt: now() }; save(); audit(req, 'CONNECTOR_PAIRING_CREATED', { pairingId }); res.json({ pairingId, code, expiresInSeconds: 600, message: 'Enter this one-time code in the local connector agent.' }); });
  app.post('/api/connector/register', (req, res) => { const { pairingId, code, deviceName } = req.body || {}; const c = state.connectors[pairingId]; if (!c || c.status !== 'PAIRING' || c.pairingCode !== String(code) || Date.now() - Date.parse(c.createdAt) > 600000) return res.status(401).json({ error: 'INVALID_PAIRING' }); c.status = 'ONLINE'; c.deviceName = String(deviceName || 'Shop Print Connector').slice(0, 100); const rawToken = crypto.randomBytes(32).toString('hex'); c.tokenHash = crypto.createHash('sha256').update(rawToken).digest('hex'); c.updatedAt = now(); save(); res.json({ connectorId: c.id, token: rawToken, shopId: c.shopId }); });
  function connectorAuth(req, res, next) { const token = req.headers.authorization?.replace(/^Bearer\s+/i, ''); const digest = token && crypto.createHash('sha256').update(token).digest('hex'); const c = Object.values(state.connectors).find(x => x.tokenHash === digest && ['ONLINE', 'BUSY'].includes(x.status)); if (!c) return res.status(401).json({ error: 'CONNECTOR_UNAUTHORIZED' }); req.connector = c; next(); }
  app.post('/api/connector/heartbeat', connectorAuth, (req, res) => { req.connector.status = ['ONLINE', 'BUSY', 'OFFLINE', 'ERROR'].includes(req.body?.status) ? req.body.status : 'ONLINE'; req.connector.printerName = String(req.body?.printerName || '').slice(0, 100); req.connector.updatedAt = now(); save(); res.json({ ok: true }); });
  app.get('/api/connector/jobs/:jobId/file', connectorAuth, (req, res) => { const j = state.printJobs[req.params.jobId]; if (!j || j.shopId !== req.connector.shopId) return res.status(404).json({ error: 'JOB_NOT_FOUND' }); const upload = uploads.get(j.file_reference); if (!upload || !fs.existsSync(upload.path)) return res.status(404).json({ error: 'FILE_EXPIRED' }); res.type(upload.mimeType).sendFile(path.resolve(upload.path)); });
  app.get('/api/connector/jobs', connectorAuth, (req, res) => { const jobs = Object.values(state.printJobs).filter(j => j.shopId === req.connector.shopId && j.status === 'PRINT_QUEUED'); for (const j of jobs) { j.status = 'PRINTING'; j.startedAt = now(); } req.connector.status = jobs.length ? 'BUSY' : 'ONLINE'; save(); res.json({ jobs: jobs.map(j => ({ ...j, file_reference: undefined })) }); });
  app.post('/api/connector/jobs/:jobId/complete', connectorAuth, (req, res) => { const j = state.printJobs[req.params.jobId]; if (!j || j.shopId !== req.connector.shopId) return res.status(404).json({ error: 'JOB_NOT_FOUND' }); if (j.status === 'PRINTED') return res.json({ ok: true, duplicate: true }); j.status = req.body?.status === 'PRINTED' ? 'PRINTED' : 'PRINT_FAILED'; j.completedAt = now(); j.error = j.status === 'PRINT_FAILED' ? 'Connector reported print failure.' : null; const order = orders.get(j.orderId); if (order) { order.status = j.status; order.updatedAt = now(); order.message = j.error || 'Print completed.'; } req.connector.status = 'ONLINE'; save(); res.json({ ok: true, status: j.status }); });
  app.get('/api/shopkeeper/connectors', shopAuth, (req, res) => res.json({ connectors: Object.values(state.connectors).filter(c => c.shopId === req.shopkeeper.shopId).map(c => ({ id: c.id, deviceName: c.deviceName, status: c.status, updatedAt: c.updatedAt })) }));

  app.get('/api/superadmin/payment-providers', app.locals.superAdminAuth, (req, res) => { const all = Object.values(state.connections); res.json({ providers: Object.keys(adapters).map(p => ({ ...safeProvider(p), connectedShops: all.filter(c => c.provider === p && c.status === 'CONNECTED').length, successes: state.providerStats[p].successes, failures: state.providerStats[p].failures })) }); });
  app.get('/api/superadmin/connector-health', app.locals.superAdminAuth, (req, res) => { const jobs = Object.values(state.printJobs); res.json({ totalConnectors: Object.keys(state.connectors).length, online: Object.values(state.connectors).filter(c => c.status === 'ONLINE').length, offline: Object.values(state.connectors).filter(c => c.status === 'OFFLINE').length, errors: Object.values(state.connectors).filter(c => c.status === 'ERROR').length, queued: jobs.filter(j => j.status === 'PRINT_QUEUED').length, failed: jobs.filter(j => j.status === 'PRINT_FAILED').length }); });
  app.get('/api/superadmin/file-processing', app.locals.superAdminAuth, (req, res) => { res.json({ activeUploads: uploads.size, processingJobs: Object.values(state.processing).filter(x => x.status === 'PROCESSING').length, cleanupJobs: Object.values(state.cleanup).filter(x => x.status === 'PENDING').length, failedProcessing: Object.values(state.processing).filter(x => x.status === 'FAILED').length }); });

  app.locals.optimizeUpload = (filePath, mimeType) => { const processingId = id('proc'); const size = fs.statSync(filePath).size; const status = 'OPTIMIZATION_SKIPPED_NO_SAFE_TOOL'; state.processing[processingId] = { id: processingId, mimeType, originalSize: size, processedSize: size, status, createdAt: now(), completedAt: now() }; save(); return { path: filePath, processingId, status }; };
  app.locals.productionConnectorRelease = async order => { const connector = connectorFor(order.shopId); if (!connector) throw new Error('PRINTER_UNAVAILABLE'); const job = { id: id('pjob'), orderId: order.id, shopId: order.shopId, printerId: connector.id, file_reference: order.uploadRef, copies: order.copies, print_type: order.printType, page_range: order.pageSelection, status: 'PRINT_QUEUED', createdAt: now(), startedAt: null, completedAt: null, error: null }; state.printJobs[job.id] = job; save(); return { connectorJobId: job.id, printerId: connector.id, deferred: true }; };
  app.locals.paymentProviderState = () => state;
  save();
};
