#!/usr/bin/env node
const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const port = 8920 + Math.floor(Math.random() * 100);
const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'printer-auto-audit-'));
const base = `http://127.0.0.1:${port}`;
const sleep = ms => new Promise(r => setTimeout(r, ms));
async function req(p, options = {}) { const r = await fetch(base + p, options); const text = await r.text(); let body; try { body = JSON.parse(text); } catch { body = { text }; } return { status:r.status, headers:r.headers, body }; }
function cookies(r) { const raw = r.headers.get('set-cookie') || ''; return raw.split(/, (?=[^;]+=)/).map(x=>x.split(';')[0]).filter(Boolean).join('; '); }
function csrf(cookie) { return cookie.match(/(?:^|; )csrf_token=([^;]+)/)?.[1] || ''; }
function sigCashfree(body, ts) { return crypto.createHmac('sha256','audit-secret').update(ts + body).digest('base64'); }
async function main() {
  const env = { ...process.env, NODE_ENV:'production', PORT:String(port), PRINTER_AUTO_DATA_DIR:dataDir, SUPERADMIN_PASSWORD:'Audit-Admin-Password-2026!', SUPERADMIN_IDENTIFIER:'audit-admin@example.test', BOOTSTRAP_SHOPKEEPER_PASSWORD:'Audit-Shopkeeper-Password-2026!', BOOTSTRAP_SHOPKEEPER_IDENTIFIER:'audit-shopkeeper@example.test', CASHFREE_CLIENT_ID:'audit-client', CASHFREE_CLIENT_SECRET:'audit-secret', CASHFREE_MERCHANT_ACCOUNT_ID:'merchant-audit', PAYMENT_WEBHOOK_SECRET:'audit-secret', TRUSTED_ORIGINS:'https://trusted.example' };
  const child = spawn(process.execPath,['server.js'],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']}); let ready=false; child.stdout.on('data',d=>{if(String(d).includes('running')) ready=true}); child.stderr.on('data',d=>process.stderr.write(String(d)));
  for(let i=0;i<60&&!ready;i++){await sleep(100);try{if((await req('/api/shops/demo-shop')).status===200)ready=true}catch{}}
  if(!ready) throw Error('server did not start');
  const login=await req('/api/shopkeeper/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier:'audit-shopkeeper@example.test',password:'Audit-Shopkeeper-Password-2026!'})}); const cookie=cookies(login), tokenHeaders={cookie,'x-csrf-token':decodeURIComponent(csrf(cookie))};
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'); const form=new FormData(); form.append('shopId','demo-shop'); form.append('file',new Blob([png],{type:'image/png'}),'audit.png'); const up=await req('/api/uploads',{method:'POST',body:form}); if(up.status!==201) throw Error('upload failed '+JSON.stringify(up.body));
  const orderRes=await req('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({shopId:'demo-shop',uploadRef:up.body.uploadRef,printType:'bw',copies:1,pageSelection:{mode:'all'},paymentMethod:'online'})}); const orderId=orderRes.body.order.id, amount=orderRes.body.order.amount;
  const started=await req('/api/shopkeeper/payment/connect',{method:'POST',headers:{...tokenHeaders,'content-type':'application/json'},body:JSON.stringify({provider:'cashfree'})}); if(started.status!==202) throw Error('connect start failed '+JSON.stringify(started.body));
  const callbackBody=JSON.stringify({onboardingId:started.body.onboardingId,merchantAccountId:'merchant-audit',providerTransactionId:'onboard-tx-1'}); const ts=String(Date.now()); const cb=await req('/api/shopkeeper/payment/callback',{method:'POST',headers:{...tokenHeaders,'content-type':'application/json','x-webhook-timestamp':ts,'x-cashfree-signature':sigCashfree(callbackBody,ts)},body:callbackBody}); if(cb.status!==200) throw Error('official callback verification failed '+JSON.stringify(cb.body));
  const pair=await req('/api/shopkeeper/connectors/pair',{method:'POST',headers:{...tokenHeaders,'content-type':'application/json'},body:'{}'}); const reg=await req('/api/connector/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pairingId:pair.body.pairingId,code:pair.body.code,deviceName:'audit'})}); const connectorToken=reg.body.token;
  await req('/api/connector/heartbeat',{method:'POST',headers:{authorization:'Bearer '+connectorToken,'content-type':'application/json'},body:JSON.stringify({status:'ONLINE',printerName:'audit-printer'})});
  const badAmount=JSON.stringify({eventId:'bad-amount',orderId,providerTransactionId:'tx-bad',amount:amount+1,currency:'INR',merchantAccountId:'merchant-audit',status:'PAID'}); const badTs=String(Date.now()); const bad=await req('/api/webhooks/cashfree',{method:'POST',headers:{'content-type':'application/json','x-webhook-timestamp':badTs,'x-cashfree-signature':sigCashfree(badAmount,badTs)},body:badAmount}); if(bad.status!==400) throw Error('amount mismatch accepted');
  const body=JSON.stringify({eventId:'event-1',orderId,providerTransactionId:'tx-1',amount,currency:'INR',merchantAccountId:'merchant-audit',status:'PAID'}); const ts2=String(Date.now()); const paid=await req('/api/webhooks/cashfree',{method:'POST',headers:{'content-type':'application/json','x-webhook-timestamp':ts2,'x-cashfree-signature':sigCashfree(body,ts2)},body}); if(paid.status!==200 || paid.body.orderStatus!=='PRINT_QUEUED') throw Error('verified payment did not queue');
  const replay=await req('/api/webhooks/cashfree',{method:'POST',headers:{'content-type':'application/json','x-webhook-timestamp':ts2,'x-cashfree-signature':sigCashfree(body,ts2)},body}); if(!replay.body.duplicate) throw Error('webhook replay was not idempotent');
  const jobs=await req('/api/connector/jobs',{headers:{authorization:'Bearer '+connectorToken}}); if(jobs.body.jobs.length!==1) throw Error('duplicate print job created'); const job=jobs.body.jobs[0];
  const falseComplete=await req('/api/connector/jobs/'+job.id+'/complete',{method:'POST',headers:{authorization:'Bearer '+connectorToken,'content-type':'application/json'},body:JSON.stringify({result:'PRINTED'})}); if(falseComplete.status!==409) throw Error('unproven print completion accepted');
  const complete=await req('/api/connector/jobs/'+job.id+'/complete',{method:'POST',headers:{authorization:'Bearer '+connectorToken,'content-type':'application/json'},body:JSON.stringify({result:'PRINTED',completionToken:job.completionToken,evidence:{printerName:'audit-printer',verifiedAt:new Date().toISOString(),exitCode:0,localJobId:'audit-local-1'}})}); if(complete.status!==200 || complete.body.status!=='PRINTED') throw Error('valid print completion rejected');
  const duplicateComplete=await req('/api/connector/jobs/'+job.id+'/complete',{method:'POST',headers:{authorization:'Bearer '+connectorToken,'content-type':'application/json'},body:JSON.stringify({result:'PRINTED',completionToken:job.completionToken,evidence:{printerName:'audit-printer',verifiedAt:new Date().toISOString(),exitCode:0,localJobId:'audit-local-1'}})}); if(!duplicateComplete.body.duplicate) throw Error('duplicate print completion not idempotent');
  const revoke=await req('/api/shopkeeper/connectors/'+reg.body.connectorId+'/revoke',{method:'POST',headers:{...tokenHeaders}}); if(revoke.status!==200) throw Error('connector revoke failed'); const revokedHeartbeat=await req('/api/connector/heartbeat',{method:'POST',headers:{authorization:'Bearer '+connectorToken,'content-type':'application/json'},body:'{}'}); if(revokedHeartbeat.status!==401) throw Error('revoked connector token still worked');
  const malformedForm=new FormData(); malformedForm.append('shopId','demo-shop'); malformedForm.append('file',new Blob([Buffer.from('not-a-real-png')],{type:'image/png'}),'bad.png'); const malformed=await req('/api/uploads',{method:'POST',body:malformedForm}); if(malformed.status!==400) throw Error('malformed file accepted');
  child.kill('SIGTERM'); await new Promise(r=>child.once('exit',r));
  const missing=spawnSync(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,NODE_ENV:'production',PORT:String(port+1),PRINTER_AUTO_DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'printer-auto-empty-'))},encoding:'utf8'}); if(missing.status===0) throw Error('production started without Super Admin credentials');
  console.log(JSON.stringify({ok:true, assertions:['official callback signature','amount/currency/account/order identity','webhook replay idempotency','single print job','completion proof','connector revoke','malformed upload rejection','production credential startup guard']},null,2));
}
const { spawnSync } = require('child_process'); main().catch(e=>{console.error(e.stack);process.exitCode=1});
